name: dart_tech_debt
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-111.0.dev <3.0.0'

dependencies:
   path: ^1.8.0
   pub_semver: any
   pubspec_parse: any


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
